### ISSUE TITLE
Issues with findimg telegram parameters

### ISSUE THREAD

**Issue by buzzard10** [mo-azfar/OTRS-Extended-Ticket-Notification#1]
Hello
i have an issue with turning on telegram integration.
Basically i have 6.0.28 OTRS CE. And i've created manually files from repo. And i have issue with finding TelegramAgent::Token parameter in system config. Any ideas?

**Comment by mo-azfar** [comment]
1. After dropping the files in correct location and with correct permissions, need to rebuild the config.

2. For FREE, this is only partial available. So, yeah it will not working on your side.
